import os

os.system("rm bodies/body*.urdf")
os.system("rm brains/brain*.nndf")
os.system("rm data/*.npy")
os.system("rm fitnessCurves/fitnessCurve*.txt")
os.system("rm trajectoryFamiliar/trajectory*.txt")
os.system("rm trajectoryForeign/trajectory*.txt")
os.system("rm fitness*.txt")
os.system("rm bestBrains.txt")
os.system("rm familiarFits.txt")
os.system("rm familiarFits_full.txt")
os.system("rm weights/weights*.txt")
os.system("rm familiarFitsContinued.txt")
os.system("rm foreignFits.txt")
os.system("rm *.mov")
